wiki/web/routes.py
"""
    Routes
    ~~~~~~
"""
import os.path
from werkzeug.utils import secure_filename

from flask import Blueprint
from flask import flash
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from flask import send_file
from flask_login import current_user
from flask_login import login_required
from flask_login import login_user
from flask_login import logout_user

from wiki.core import Processor
from wiki.web.forms import EditorForm, RegisterForm
from wiki.web.forms import LoginForm
from wiki.web.forms import SearchForm
from wiki.web.forms import URLForm
from wiki.web import current_wiki
from wiki.web import current_users
from wiki.web.user import protect, User
from wiki.web.user import UserManager

bp = Blueprint('wiki', __name__)


@bp.route('/')
@protect
def home():
    page = current_wiki.get('home')
    if page:
        return display('home')
    return render_template('home.html')


@bp.route('/index/')
@protect
def index():
    pages = current_wiki.index()
    return render_template('index.html', pages=pages)


@bp.route('/<path:url>/')
@protect
def display(url):
    page = current_wiki.get_or_404(url)
    return render_template('page.html', page=page)


@bp.route('/create/', methods=['GET', 'POST'])
@protect
def create():
    form = URLForm()
    if form.validate_on_submit():
        return redirect(url_for(
            'wiki.edit', url=form.clean_url(form.url.data)))
    return render_template('create.html', form=form)


@bp.route('/edit/<path:url>/', methods=['GET', 'POST'])
@protect
def edit(url):
    page = current_wiki.get(url)
    form = EditorForm(obj=page)
    if form.validate_on_submit():
        if not page:
            page = current_wiki.get_bare(url)
        form.populate_obj(page)
        page.save()
        flash('"%s" was saved.' % page.title, 'success')
        return redirect(url_for('wiki.display', url=url))
    return render_template('editor.html', form=form, page=page)


@bp.route('/preview/', methods=['POST'])
@protect
def preview():
    data = {}
    processor = Processor(request.form['body'])
    data['html'], data['body'], data['meta'], data['headers'] = processor.process()
    return data['html']


@bp.route('/move/<path:url>/', methods=['GET', 'POST'])
@protect
def move(url):
    page = current_wiki.get_or_404(url)
    form = URLForm(obj=page)
    if form.validate_on_submit():
        newurl = form.url.data
        current_wiki.move(url, newurl)
        return redirect(url_for('wiki.display', url=newurl))
    return render_template('move.html', form=form, page=page)


@bp.route('/delete/<path:url>/')
@protect
def delete(url):
    page = current_wiki.get_or_404(url)
    current_wiki.delete(url)
    flash('Page "%s" was deleted.' % page.title, 'success')
    return redirect(url_for('wiki.home'))


@bp.route('/tags/')
@protect
def tags():
    tags = current_wiki.get_tags()
    return render_template('tags.html', tags=tags)


@bp.route('/tag/<string:name>/')
@protect
def tag(name):
    tagged = current_wiki.index_by_tag(name)
    return render_template('tag.html', pages=tagged, tag=name)


@bp.route('/search/', methods=['GET', 'POST'])
@protect
def search():
    form = SearchForm()
    if form.validate_on_submit():
        results = current_wiki.search(form.term.data, form.ignore_case.data)
        return render_template('search.html', form=form,
                               results=results, search=form.term.data)
    return render_template('search.html', form=form, search=None)


@bp.route('/user/login/', methods=['GET', 'POST'])
def user_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = current_users.get_user(form.name.data)
        login_user(user)
        user.set('authenticated', True)
        flash('Login successful.', 'success')
        return redirect(request.args.get("next") or url_for('wiki.index'))
    return render_template('login.html', form=form)


@bp.route('/user/logout/')
@login_required
def user_logout():
    current_user.set('authenticated', False)
    logout_user()
    flash('Logout successful.', 'success')
    return redirect(url_for('wiki.index'))


@bp.route('/user/')
def user_index():
    pass


"""Route used for creating a new user"""


@bp.route('/user/create/', methods=['GET', 'POST'])
def user_create():
    form = RegisterForm()
    if form.validate_on_submit():
        form.add_new_user(form.name.data, form.password.data)
        return redirect(request.args.get("next") or url_for('wiki.index'))
    return render_template('register.html', form=form)


@bp.route('/user/<int:user_id>/')
def user_admin(user_id):
    pass


@bp.route('/user/delete/<int:user_id>/')
def user_delete(user_id):
    pass

@bp.route('/upload/', methods=['GET', 'POST'])
@protect
def upload():
    """
    This function uploads a given file if all requirements are met.
    """
    # Check if they are trying to "POST" a file
    if request.method == 'POST':
        # Get the file and assign it to a variable
        f = request.files['file']

        # Make sure the filename is secure (e.g. no spaces in name) and then split it
        filename = secure_filename(f.filename)
        file, extension = os.path.splitext(filename)

        # Run a while loop to check if name already exists.
        counter = 1
        while os.path.exists(os.path.join('content', filename)):
            # If name already exists, rename it with a number.
            filename = file + "(" + str(counter) + ")" + extension
            counter += 1

        # Check to see if the extension is indeed a markdown file.
        if filename.split('.')[-1] == 'md':
            # The next three lines reads the whole file, finds the size, and then converts it back to normal.
            f.seek(0, 2)
            size = f.tell()
            f.seek(0, 0)
            # Check to see if file size is under 100MB.
            if size <= 100:
                # If all requirements are met, save the file under the content folder and print a success message.
                f.save(os.path.join('content', filename))
                flash(f"File {filename} uploaded successfully")
                return render_template('upload.html')
            # If size is not under 100MB, print an error message.
            else:
                flash("Error: file size must be under 100MB")
                return render_template('upload.html')
        # If file extension not .md, print an error message.
        else:
            flash("Error: file extension must be .md")
            return render_template('upload.html')
    # Render upload.html when first viewing page
    else:
        return render_template('upload.html')


@bp.route('/tomd/<path:url>')
def tomd(url):
    """
    This function grabs the url of the file and allows you to download it
    """
    # Path from current directory to content directory
    path = f"../../content/{url}.md"
    # the send_file() function is built-in to Flask to download files
    return send_file(path, as_attachment=True)

@bp.route('/topdf/<path:url>/')
def topdf(url):
    """
    topdf is called on the current page. So it gets the url for the current page and then sends it to the
    converter function which will return a file to the converted file. It then creates a preview window in a
    separate tab in the browser that will let the user view the pdf file and download it.
    """
    page = current_wiki.get(url)
    file = current_wiki.topdf(page)
    return send_file(file, as_attachment=True)


@bp.route('/totxt/<path:url>/')
def totxt(url):
    """
    totxt is called on the current page. So it gets the url for the current page and then sends it to the
    converter function which will return a file to the converted file in this case a palin text file.
    Then it sends that file as an attachment to the user.
    """
    page = current_wiki.get(url)
    file = current_wiki.totxt(page)
    return send_file(file, as_attachment=True)


@bp.route('/tohtml/<path:url>')
def tohtml(url):
    """
    tohtml is called on the current page. So it gets the url for the current page and then sends it to the
    converter function which will return a file to the converted file in this case an html document.
    Then it sends that file as an attachment to the user.
    """
    page = current_wiki.get(url)
    file = current_wiki.tohtml(page)
    return send_file(file, as_attachment=True)


"""
    Error Handlers
    ~~~~~~~~~~~~~~
"""


@bp.errorhandler(404)
def page_not_found(error):
    return render_template('404.html'), 404

wiki/web/templates/base.html
{% from "helpers.html" import input %}
<!DOCTYPE html>
<html>
	<head>
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap.css') }}">
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='responsive.css') }}">
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='pygments.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
	</head>

	<body>
		<div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<div class="row">
						<div class="span12">
							<a href="#" class="brand">{{ config.TITLE }}</a>
							<ul class="nav">
								<li><a href="{{ url_for('wiki.home') }}">Home</a></li>
								<li><a href="{{ url_for('wiki.index') }}">Index</a></li>
								<li><a href="{{ url_for('wiki.tags') }}">Tags</a></li>
								<li><a href="{{ url_for('wiki.search') }}">Search</a></li>
								<li class="divider-vertical"></li>
								<li><a href="{{ url_for('wiki.create') }}">New Page</a></li>
								<li class="divider-vertical"></li>
                                <li><a href="{{ url_for('wiki.upload') }}">Upload Page</a></li>
								<li class="divider-vertical"></li>
								<li></li>
							</ul>

							<ul class="nav pull-right">
								{% if current_user.is_anonymous %}
									<li><a href="{{ url_for('wiki.user_login') }}">Login</a></li>
								{% else %}
									<li><a href="{{ url_for('wiki.user_logout') }}">Logout</a></li>
								{% endif %}
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="container">
			<div class="row">
				<div class="span10 offset1">
					{% block header %}
						<div class="page-header">
							<h1>{% block title %}{{ page.title }}{% endblock title %}</h1>
						</div>
					{% endblock header %}
				</div>
			</div>
			<div class="row">
				<div class="span7 offset1">
					{% with messages = get_flashed_messages(with_categories=True) %}
						{% if messages %}
							{% for category, message in messages %}
								<div class="alert alert-{{ category }}">
									<button type="button" class="close" data-dismiss="alert">&times;</button>
									{{ message }}
								</div>
							{% endfor %}
						{% endif %}
					{% endwith %}
					{% if form and form.errors %}
						<div class="alert alert-error">Errors occured verifying your input. Please check the marked fields below.</div>
					{% endif %}
					{% block content %}
					{% endblock content %}
				</div>
				<div class="span3">
					{% block sidebar %}
					{% endblock sidebar %}
				</div>
			</div>
		</div>
		<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.9.0/jquery.min.js "></script>
		<script type="text/javascript">
			if (typeof jQuery == 'undefined') {
				document.write(unescape("%3Cscript src='{{ url_for('static', filename='jquery.min.js') }}' type='text/javascript'%3E%3C/script%3E"));
			}
		</script>
		<script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
		<script type="text/javascript">
			{% block postscripts %}
			{% endblock postscripts %}
		</script>
	</body>
</html>

wiki/web/templates/create.html
{% extends "base.html" %}

{% block title %}Create a new page{% endblock title %}
{% block content %}
<form method="POST" class="form-inline">
	{{ form.hidden_tag() }}
	{{ input(form.url, placeholder="URL of the new page", autocomplete="off") }}
	<input type="submit" class="btn btn-success" value="Create">
</form>
{% endblock content %}

{% block sidebar %}
<p class="alert alert-success">Thank you for creating new content!</p>
{% endblock sidebar %}

wiki/web/templates/editor.html
{% extends "base.html" %}

{% block title -%}
Wiki Editor
{%- endblock title %}

{% block content %}
<ul class="nav nav-tabs">
	<li class="active"><a href="#editor" data-toggle="tab">Editor</a></li>
</ul>
<div class="tab-content">
	<div class="tab-pane active" id="editor">
		<form method="post" class="form">
			{{ form.hidden_tag() }}
			{{ input(form.title, placeholder="Title", class="span7", autocomplete="off") }}
            <h3>Preview</h3>
            <div id="preview"></div>
            <div class="editor">
                <div class="editor-buttons">
                    <button type="button" onclick="boldContent()" class="editor-btn">Bold</button>
                    <button type="button" onclick="italicContent()" class="editor-btn">Italics</button>
                    <button type="button" onclick="hContent('#')" class="editor-btn">H1</button>
                    <button type="button" onclick="hContent('##')" class="editor-btn">H2</button>
                    <button type="button" onclick="hContent('###')" class="editor-btn">H3</button>
                    <button type="button" onclick="hContent('*')" class="editor-btn">Unordered List</button>
                    <button type="button" onclick="hContent('1.')" class="editor-btn">Ordered List</button>
                </div>
			    {{ input(form.body, placeholder="Markdown", class="span7", rows="10", id="editor-text") }}
            </div>
			{{ input(form.tags, placeholder="Tags (comma separated)", class="span7", autocomplete="off") }}
			<div class="form-actions">
				<div class="pull-right">
          <a class="btn" href="{{ url_for('wiki.display', url=page.url) }}">Cancel</a>
					<button class="btn btn-success" type="submit">Save</button>
				</div>
			</div>
		</form>
	</div>
</div>
{% endblock content %}

{% block sidebar %}
<h3>Editor How-To</h3>
<p>This editor is <a href="http://daringfireball.net/projects/markdown/">markdown</a> featured.</p>
<pre><code>* I
* am
* a
* list</code></pre>
Turns into:
<ul>
<li>I</li>
<li>am</li>
<li>a</li>
<li>list</li>
</ul>
<p><code>**bold** and *italics*</code> turn into <strong>bold</strong> and <em>italics</em>. Very easy!</p>
<p>Create links with <code>[NoTube](http://www.notube.com)</code>. They turn into <a href="http://www.notube.com">NoTube</a>.</p>
<p>Headers are as follows:</p>
<pre><code># Level 1
## Level 2
### Level 3</code></pre>
<p></p>

{% endblock sidebar %}

{% block postscripts -%}
{{ super() }}
const headerRegex = /##*/
    function showPreview() {
	var $form = $('.form');
  var $inputs = $form.find('input, textarea, button');
  var $pre = $('#preview');
  var bodycontent = 'title: preview\n\n' + $form.find('textarea').val();
  $.ajax({
    url: "{{ url_for('wiki.preview') }}",
    type: "POST",
    data: { body: bodycontent },
    success: function(msg) {
      $pre.html(msg);
    },
    error: function() {
			$pre.addClass('alert').addClass('alert-error');
      $pre.html('There was a problem with the preview.');
    },
  });
}

function boldContent() {
    let txtarea = document.getElementById("editor-text");
    let currentVal = txtarea.value;
    //Get start and end of highlighted selection
    const start = txtarea.selectionStart;
    const end = txtarea.selectionEnd;
    //Make sure a selection was made
    if (start === end) {
        return;
    }
    const selectedText = currentVal.substring(start, end);
    let newSelectedText = ''
    selectedText.split(' ').map((word) => {
        //If a blank space is selected simply add the space and skip over it
        if (word === '') {
            newSelectedText += ' ';
        }
        else if (word.match(headerRegex) !== null) {
            newSelectedText += word + ' ';
        }
        else {
            //Check if it's already bolded
            if (word.substring(0, 2) === '**' && word.substring(word.length - 2) === '**') {
                newSelectedText += word.substring(2, word.length - 2) + ' ';
            }
            else {
                newSelectedText += `**${word}** `;
            }
        }
    });
    newSelectedText = newSelectedText.trim();
    currentVal = currentVal.replace(selectedText, newSelectedText);
    txtarea.value = currentVal;
    showPreview();
}

function italicContent() {
    let txtarea = document.getElementById("editor-text");
    let currentVal = txtarea.value;
    //Get start and end of highlighted selection
    const start = txtarea.selectionStart;
    const end = txtarea.selectionEnd;
    //Make sure a selection was made
    if (start === end) {
        return;
    }
    const selectedText = currentVal.substring(start, end);
    let newSelectedText = ''
    selectedText.split(' ').map((word) => {
        //If a blank space is selected simply add the space and skip over it
        if (word === '') {
            newSelectedText += ' ';
        }
        //Skip # headers
        else if (word.match(headerRegex) !== null) {
            newSelectedText += word + ' ';
        }
        else {
            //Check if it's already italic AND bold
            if ((word.substring(0, 3) === '***' && word.substring(word.length - 3) === '***') ||
                    (word.substring(0, 1) === '*' && word.substring(word.length - 1) === '*'
                && word.substring(0, 2) !== '**' && word.substring(word.length - 2) !== '**')) {
                newSelectedText += word.substring(1, word.length - 1) + ' ';
            }
            else {
                newSelectedText += `*${word}* `;
            }
        }
    });
    newSelectedText = newSelectedText.trim();
    currentVal = currentVal.replace(selectedText, newSelectedText);
    txtarea.value = currentVal;
    showPreview();
}

    function hContent(amt) {
        let txtarea = document.getElementById("editor-text");
        let currentVal = txtarea.value;
        //Get start and end of highlighted selection
        const start = txtarea.selectionStart;
        const end = txtarea.selectionEnd;
        const selectedText = currentVal.substring(start, end);
        //If something is highlighted
        if (start !== end) {
            //Split at newlines checking the beginning of each line for existing header tags
            let newVals = selectedText.split("\n").map((str) => {
                //If header already exists, remove it
                if (str.slice(0, amt.length) === amt)
                {
                    return str.slice(1 + amt.length);
                }
                return `${amt} ${str}`;
            });
            currentVal = currentVal.replace(selectedText, newVals.join("\n"));
        }
        //Nothing highlighted
        else {
            let index = start;
            let lastNewLine = 0;
            for (var i = 0; i < index; i++) {
              if (currentVal.charAt(i) === '\n') {
                lastNewLine = i
                }
            }
            if (lastNewLine === 0) {
                lastNewLine -= 1;
            }
            //Already has h heading
            if (currentVal.slice(lastNewLine + 1, lastNewLine + 1 + amt.length) === amt)
            {
                currentVal = currentVal.slice(0, lastNewLine + 1) + currentVal.slice(lastNewLine + 2 + amt.length)
            }
            else {
                currentVal = currentVal.slice(0, lastNewLine + 1) + amt + ' ' + currentVal.slice(lastNewLine+1);
            }
        }
        txtarea.value = currentVal;
        showPreview();
    }

    document.getElementById("editor-text").addEventListener("keyup", (event) => {
        showPreview();
    });
    showPreview();
{%- endblock postscripts %}

wiki/web/templates/helpers.html
{% macro input(field) -%}
	<div class="control-group {% if field.errors %}error{% endif %}">
		{% if field.type == 'BooleanField' %}
			<div class="controls">
				<label for="{{ field.name }}" class="checkbox">
					{{ field(**kwargs) }}
					{{ field.label.text }}
				</label>
			</div>
		{% else %}
			<label for="{{ field.name }}" class="control-label">{{ field.label.text }}</label>
			<div class="controls">
				{{ field(**kwargs) }}
				{% if field.errors %}
					<div>
						{% for error in field.errors %}
							<span class="help-inline">
								{{ error }}
							</span>
						{% endfor %}
					</div>
				{% endif %}
			</div>
		{% endif %}
	</div>
{%- endmacro %}

wiki/web/templates/home.html
{% extends "base.html" %}
{% block title -%}
	Welcome to your new wiki!
{% endblock title %}

{% block content %}
<p>You did not create any content yet. Your wiki recommends you, to do so now, as every user will see this page first, and you would want to make a good impression, wouldn't you?</p>
<p><a href="{{ url_for('wiki.edit', url='home') }}" class="btn btn-success">Create a homepage</a></p>
{% endblock %}

wiki/web/templates/index.html
{% extends "base.html" %}

{% block title %}Page Index{% endblock title %}

{% block content %}
{% if pages %}
	<table class="table">
		<thead>
			<tr>
				<th>Title</th>
				<th>URL</th>
			</tr>
		</thead>
		<tbody>
			{% for page in pages %}
				<tr>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.title }}</a></td>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.url }}</a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
	<p>There are no pages yet.</p>
{% endif %}
{% endblock content %}

{% block sidebar %}
<ul class="nav nav-tabs nav-stacked">
	<li><a href="{{ url_for('wiki.create') }}">New Page</a></li>
	<li><a href="{{ url_for('wiki.tags') }}">Tag List</a></li>
	<li><a href="{{ url_for('wiki.search') }}">Search</a></li>
</ul>
{% endblock sidebar %}

wiki/web/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock title %}

{% block content %}
<form class="form form-inline" method="POST">
	{{ form.hidden_tag() }}
	{{ form.name(placeholder='Username') }}
	{{ form.password(placeholder='Password') }}
	<input type="submit" class="btn btn-primary" value="Login">
</form>
    <p>Need a new account? <a href="http://127.0.0.1:5000/user/create">Register Here.</a></p>
{% endblock content %}

wiki/web/templates/move.html
{% extends "base.html" %}

{% block title %}Move a page{% endblock title %}
{% block content %}
<form method="POST" class="form-inline">
    {{ form.hidden_tag() }}
    {{ input(form.url, placeholder="New URL of the page", autocomplete="off") }}
    <input type="submit" class="btn btn-success" value="Create">
</form>
{% endblock content %}

{% block sidebar %}
<p class="alert alert-success">Be careful, the old url will be invalid immediately!</p>
{% endblock sidebar %}

wiki/web/templates/page.html
{% extends "base.html" %}

{% block title %}
    {{ page.title }}
{% endblock title %}

{% block content %}
    <div id="confirmDelete" class="modal hide fade" aria-hidden="true">
        <div class="modal-header">
            <h3>Are you sure?</h3>
        </div>
        <div class="modal-body">
            <p>Are you sure you want to delete {{ page.title }}? This cannot be undone.</p>
        </div>
        <div class="modal-footer">
            <a href="#" class="btn" data-dismiss="modal" aria-hidden="true">No</a>
            <a href="{{ url_for('wiki.delete', url=page.url) }}" class="btn btn-danger">Yes, delete.</a>
        </div>
    </div>
    {{ page }}
{% endblock content %}

{% block sidebar %}
{% if page.headers %}
    <h3>Headers</h3>
    <ul>
        {% for header in page.headers %}
            <li><a>{{ header }}</a></li>
        {% endfor %}
    </ul>
{% endif %}
{% if page.tags %}
<h3>Tags</h3>
  <ul>
      {% for tag in page.tags.split(',') %}
        <li><a href="{{ url_for('wiki.tag', name=tag.strip()) }}">{{ tag|trim }}</a></li>
      {% endfor %}
  </ul>
{% endif %}
<h3>Actions</h3>
<ul class="nav nav-tabs nav-stacked">
    <li><a href="{{ url_for('wiki.edit', url=page.url) }}">Edit</a></li>
    <li><a href="{{ url_for('wiki.move', url=page.url) }}">Move</a></li>
    <li><a href="{{ url_for('wiki.tomd', url=page.url) }}">Download Markdown</a></li>
    <li><a href ="{{ url_for('wiki.topdf', url = page.url) }}" target="_blank"
           rel="noopener noferrer">Convert to PDF</a></li>
    <li><a href ="{{ url_for('wiki.totxt', url = page.url) }}" target="_blank"
           rel="noopener noferrer">Convert to Text</a></li>
    <li><a href ="{{ url_for('wiki.tohtml', url = page.url) }}" target="_blank"
           rel="noopener noferrer">Convert to HTML</a></li>

    <li><a href="#confirmDelete" data-toggle="modal" class="text-error">Delete</a></li>

</ul>
{% endblock sidebar %}
{% block postscripts %}
    $("h1,h2").each(function(){
    $(this).attr("id", $(this).text().replace(/\s+/g,''));
    });
    $("div .span3 ul:first li a").each(function(){
    const textToReplace = $(this).text();
    const newText = '#' + textToReplace.replace(/\s+/g,'');
    $(this).attr("href", newText);
    });
{% endblock %}

wiki/web/templates/register.html
{% extends "base.html" %}

{% block title %}Register New User{% endblock title %}

{% block content %}
<form class="form form-inline" method="POST">
	{{ form.hidden_tag() }}
	{{ form.name(placeholder='Username') }}
	{{ form.password(placeholder='Password') }}
	<input type="submit" class="btn btn-primary" value="Register">
</form>
{% endblock content %}

wiki/web/templates/search.html
{% extends "base.html" %}

{% block title %}
{% if search %}
	Results for "{{ search }}"
{% else %}
	Search
{% endif %}
{% endblock title %}

{% block content %}
<div class="row">
	<div class="span8 offset1">
		<form class="form-inline well" method="POST">
			{{ form.hidden_tag() }}
			{{ form.term(placeholder='Search for.. (regex accepted)', autocomplete="off") }}
            {{ form.ignore_case() }} Ignore Case
			<input type="submit" class="btn btn-success pull-right" value="Search!">
		</form>
	</div>
</div>

{% if search %}
	{% if results %}
		<ul>
			{% for result in results %}
				<li><a href="{{ url_for('wiki.display', url=result.url) }}">{{ result.title }}</a></li>
			{% endfor %}
		</ul>
	{% else %}
		<p>No results for your search.</p>
	{% endif %}
{% endif %}
{% endblock content %}

wiki/web/templates/tag.html
{% extends "base.html" %}

{% block title %}Pages tagged {{ tag }}{% endblock title %}

{% block content %}
{% if pages %}
	<table class="table">
		<thead>
			<tr>
				<th>Title</th>
				<th>URL</th>
			</tr>
		</thead>
		<tbody>
			{% for page in pages %}
				<tr>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.title }}</a></td>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.url }}</a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
	<p>There are no pages tagged {{ tag }}.</p>
{% endif %}
{% endblock content %}

wiki/web/templates/tags.html
{% extends "base.html" %}

{% block title %}Index by Tags{% endblock title %}

{% block content %}
{% if tags %}
	<table class="table">
		<thead>
			<tr>
				<th>Tag</th>
				<th>Number of Articles</th>
			</tr>
		</thead>
		<tbody>
			{% for tag, pages in tags|dictsort %}
				<tr>
					<td><a href="{{ url_for('wiki.tag', name=tag) }}">{{ tag }}</a></td>
					<td>{{ pages|length }}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
	<p>There are no tags in use so far.</p>
{% endif %}
{% endblock content %}

wiki/web/templates/upload.html
<!-- Extends base.html to keep the same web design through every page -->
{% extends "base.html" %}

<!-- Title at the top of the page in bold -->
{% block title %}
    Upload a file
{% endblock title %}

{% block content %}
    <!-- This form is for uploading a file -->
    <!-- It requires the POST request and mutipart/form-data is used for files-->
    <form action="/upload/" method="POST" enctype="multipart/form-data" class="form-inline">
	    <input type=file name=file>
        <input type="submit" class="btn btn-success" value="Upload">
    </form>
{% endblock content %}

<!-- Side comment thanking the user for uploading a file. Similar to the create page -->
{% block sidebar %}
    <p class="alert alert-success">Thank you for uploading new content!</p>
{% endblock sidebar %}